In [44]:
import numpy as np

A = np.random.rand(3, 4)
B = np.random.rand(4, 5)

A, B, np.einsum('ij,jk->ik', A, B)


(array([[0.46900866, 0.93443552, 0.19270161, 0.55608824],
        [0.19776413, 0.28218186, 0.4973711 , 0.34539141],
        [0.20529319, 0.72273246, 0.89419725, 0.2827094 ]]),
 array([[0.22526189, 0.52368148, 0.60756848, 0.61973159, 0.65214266],
        [0.03211683, 0.18104348, 0.8501437 , 0.42277902, 0.8360104 ],
        [0.56224819, 0.02287917, 0.63988828, 0.16765542, 0.79120056],
        [0.89917477, 0.7791288 , 0.27426573, 0.64090183, 0.30197638]]),
 array([[0.74402754, 0.85245783, 1.3551828 , 1.07442466, 1.40744951],
        [0.64382475, 0.43513643, 0.77304134, 0.5466102 , 0.86269773],
        [0.82642256, 0.47907977, 1.38887996, 0.76388878, 1.53095322]]))

In [45]:
# free indices: Indeces that are specified in the output
# sum indices: Indeces that are not specified in the output

# rules
# 1. repeated letters in inputs will be multiplied and those products will be the output
# 2. ommitted letters in inputs will be summed and those sums will be the output
# 3. we can return the unsummed axis in any order

In [46]:
import torch
from torch import einsum
torch.manual_seed(0)

x = torch.randn((2, 3))
print(x)

# tensor permutation
# same as transpose
einsum('ij->ji', x)

# summation
einsum('ij->', x)

# column sum
einsum('ij->j', x)

# row sum
einsum('ij->i', x)

# matrix vector multiplication
v = torch.randn((1, 3))
einsum('ij,kj->ik', x, v)

# matrix matrix multiplication
einsum('ij,kj->ik', x, x)

# dot product with matrix
einsum('ij,ij->', x, x)

# square of matrix
einsum('ij,ij->ij', x, x)

# outer product
a = torch.randn((3))
b = torch.randn((5))
einsum('i,j->ij', a, b)

# batch matrix multiplication
a = torch.randn((3, 2, 5))
b = torch.randn((3, 5, 3))
einsum('ijk,ikl->ijl', a, b)

# diagonal
a = torch.randn((3, 3))
einsum('ii->i', a)

tensor([[ 1.5410, -0.2934, -2.1788],
        [ 0.5684, -1.0845, -1.3986]])
tensor([[ 0.3731, -0.1143, -0.4537],
        [ 2.3055, -0.3790, -0.4669],
        [-0.4609,  1.2652,  1.5746]])


tensor([ 0.3731, -0.3790,  1.5746])